#!/bin/bash
fftwv=3.3.1

function fail()
{
echo FATALL ERRROR in $1 stage
echo ... check output log
exit 1
}

if [ -n "$SLIM_COMP" ]; then
	echo Installing FFTW3 $fftwv in $SLIM_COMP
else
	echo FATAL ERROR: undefined environment SLIM_COMP
	exit 1
fi

# TMPDIR
export TMPDIR=/tmp/`whoami`/fftw3-${fftwv}

# set temporary installation directories
srcdir=${TMPDIR}/fftw-${fftwv}
instdir=$SLIM_COMP/external

# set prompt
PS4="\n%%%%% "
#set -x

# delete old temporary directories
test -e $TMPDIR && rm -rf $TMPDIR
test -e $srcdir && rm -rf $srcdir

# create new temporary directories
mkdir -p $TMPDIR || exit 1
cd $TMPDIR || exit 1
tar -xzf $SLIM_COMP/external/tarballs/fftw-${fftwv}.tgz || exit 1
cd $srcdir || exit 1

# CONFIGURE
echo CONFIGURATION stage
echo ... output in ${TMPDIR}/configure.fftw3-${fftwv}
$srcdir/configure \
	--prefix=$instdir \
	--enable-shared \
	--with-pic \
	--with-openmp --enable-threads \
	1>${TMPDIR}/configure.fftw3-${fftwv} 2>&1 || fail "CONFIGURATION"
echo CONFIGURATION done

# MAKE
echo BUILD stage
echo ... output in ${TMPDIR}/make_build.fftw3-${fftwv}
make -j 2 1>${TMPDIR}/make_build.fftw3-${fftwv} 2>&1 || fail "BUILD"
echo BUILD done

# INSTALL
echo INSTALLATION stage
echo ... output in ${TMPDIR}/make_install.fftw3-${fftwv}
make install 1>${TMPDIR}/make_install.fftw3-${fftwv} 2>&1 || fail "INSTALLATION"
echo INSTALL done

# clean temporary directories
echo CLEANUP stage
rm -rf $TMPDIR

echo FFTW3 installation completed
