#!/bin/bash
gccr=4.7.4

function fail()
{
echo FATALL ERRROR in $1 stage
echo ... check output log
exit 1
}

if [ -n "$SLIM_COMP" ]; then
	echo Installing GCC $gccr in $SLIM_COMP
else
	echo FATAL ERROR: undefined environment SLIM_COMP
	exit 1
fi
test_gcc && exit 0

# TMPDIR
export TMPDIR=/tmp/`whoami`/gcc-${gccr}

# set temporary installation directories
srcdir=${TMPDIR}/gcc-${gccr}
objdir=${TMPDIR}/obj
instdir=$SLIM_COMP/external

# set prompt
PS4="\n%%%%% "
#set -x

# delete old temporary directories
test -e $TMPDIR && rm -rf $TMPDIR
test -e $srcdir && rm -rf $srcdir
test -e $objdir && rm -rf $objdir

# create new temporary directories
mkdir -p $TMPDIR || exit 1
cd $TMPDIR || exit 1
tar -xzf $SLIM_COMP/external/tarballs/gcc-${gccr}-p1.tgz || exit 1
tar -xzf $SLIM_COMP/external/tarballs/gcc-${gccr}-p2.tgz || exit 1
cd $srcdir || exit 1
mkdir -p $objdir || exit 1
cd $objdir || exit 1

# CONFIGURE
echo CONFIGURATION stage
echo ... output in ${TMPDIR}/configure.gcc-${gccr}
$srcdir/configure \
	--prefix=$instdir \
	--enable-languages=c,c++,fortran \
	1>${TMPDIR}/configure.gcc-${gccr} 2>&1 || fail "CONFIGURATION"
	#--enable-shared \
	#--enable-threads=posix \
	#--disable-checking \
	#--with-system-zlib \
	#--enable-__cxa_atexit \
	#--disable-libunwind-exceptions \
	#--disable-dssi \
	#--disable-plugin \
	#--disable-werror \
echo CONFIGURATION done

# MAKE
echo BUILD stage
echo ... output in ${TMPDIR}/make_build.gcc-${gccr}
make -j 2 1>${TMPDIR}/make_build.gcc-${gccr} 2>&1 || fail "BUILD"
echo BUILD done

# INSTALL
echo INSTALLATION stage
echo ... output in ${TMPDIR}/make_install.gcc-${gccr}
make install 1>${TMPDIR}/make_install.gcc-${gccr} 2>&1 || fail "INSTALLATION"
echo INSTALL done

# clean temporary directories
echo CLEANUP stage
rm -rf $TMPDIR

echo GCC installation completed
